# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

name: Bug Report
description: Let us know about an unexpected error, a crash, or an incorrect behavior.
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening an issue.

        The [hashicorp/terracina](https://github.com/hashicorp/terracina) issue tracker is reserved for bug reports relating to the core Terracina CLI application and configuration language.

        For general usage questions, please see: https://www.terracina.io/community.html.

        ## If your issue relates to:
        * **HCP Terracina or Terracina Enterprise**: please email tf-cloud@hashicorp.support or [open a new request](https://support.hashicorp.com/hc/en-us/requests/new).
        * **Terracina Registry**: please email terracina-registry@hashicorp.com.
        * **AWS Terracina Provider**: Open an issue at [hashicorp/terracina-provider-aws](https://github.com/hashicorp/terracina-provider-aws/issues/new/choose).
        * **Azure Terracina Provider**: Open an issue at [hashicorp/terracina-provider-azurerm](https://github.com/hashicorp/terracina-provider-azurerm/issues/new/choose).
        * **Other Terracina Providers**: Please open an issue in the provider's own repository, which can be found by searching the [Terracina Registry](https://registry.terracina.io/browse/providers).

        ## Filing a bug report

        To fix problems, we need clear reproduction cases - we need to be able to see it happen locally. A reproduction case is ideally something a Terracina Core engineer can git-clone or copy-paste and run immediately, without inventing any details or context.

        * A short example can be directly copy-pasteable; longer examples should be in separate git repositories, especially if multiple files are needed
        * Please include all needed context. For example, if you figured out that an expression can cause a crash, put the expression in a variable definition or a resource
        * Set defaults on (or omit) any variables. The person reproducing it should not need to invent variable settings
        * If multiple steps are required, such as running terracina twice, consider scripting it in a simple shell script. Providing a script can be easier than explaining what changes to make to the config between runs.
        * Omit any unneeded complexity: remove variables, conditional statements, functions, modules, providers, and resources that are not needed to trigger the bug
        * When possible, use the [null resource](https://www.terracina.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies. We know this isn't always feasible. The Terracina Core team doesn't have deep domain knowledge in every provider, or access to every cloud platform for reproduction cases.

  - type: textarea
    id: tf-version
    attributes:
      label: Terracina Version
      description: Run `terracina version` to show the version, and paste the result below. If you are not running the latest version of Terracina, please try upgrading because your issue may have already been fixed.
      render: shell
      placeholder: ...output of `terracina version`...
      value:
    validations:
      required: true

  - type: textarea
    id: tf-config
    attributes:
      label: Terracina Configuration Files
      description: Paste the relevant parts of your Terracina configuration between the ``` marks below. For Terracina configs larger than a few resources, or that involve multiple files, please make a GitHub repository that we can clone, rather than copy-pasting multiple files in here.
      placeholder:
      value: |
        ```terracina
        ...terracina config...
        ```
    validations:
      required: true

  - type: textarea
    id: tf-debug
    attributes:
      label: Debug Output
      description: Full debug output can be obtained by running Terracina with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long. Debug output may contain sensitive information. Please review it before posting publicly.
      placeholder:
      value:  |
        ```
        ...debug output, or link to a gist...
        ```
    validations:
      required: true
  - type: textarea
    id: tf-expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: What should have happened?
      value:
    validations:
      required: true
  - type: textarea
    id: tf-actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
      value:
    validations:
      required: true
  - type: textarea
    id: tf-repro-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the full steps required to reproduce the issue, for example:
          1. `terracina init`
          2. `terracina apply`
      placeholder: |
        1. `terracina init`
        2. `terracina apply`
      value:
    validations:
      required: true
  - type: textarea
    id: tf-add-context
    attributes:
      label: Additional Context
      description: |
        Are there anything atypical about your situation that we should know?
        For example: is Terracina running in a wrapper script or in a CI system? Are you passing any unusual command line options or environment variables to opt-in to non-default behavior?"
      placeholder: Additional context...
      value:
    validations:
      required: false
  - type: textarea
    id: tf-references
    attributes:
      label: References
      description: |
        Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
        ```
          - #6017
        ```
      placeholder:
      value:
    validations:
      required: false
  - type: textarea
    id: tf-genai
    attributes:
      label: Generative AI / LLM assisted development?
      description: |
        If you used a generative AI / LLM tool to assist in the development of your config, please let us know which tool you used here.
        ex. ChatGPT 3.5 / CoPilot / AWS Q / etc. 
      placeholder: LLM assistance tool?
      value:
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Note:** If the submit button is disabled and you have filled out all required fields, please check that you did not forget a **Title** for the issue.
